#!/usr/bin/env python
"""
hellanzb - hella nzb

TODO:
o use optparse
o clean up the configuration options, possibly putting them in another file (that would
lie in /etc). ideally most of those settings could be overwritten via the cmd line

@author pjenvey, bbangert

"""

import os, sys, Hellanzb.Troll, Hellanzb.Ziplick
from Hellanzb.Troll import defineMusicType, error, FatalError

__id__ = "$Id"

# name of the sub directory within incomingDir to move proccessed files to
Hellanzb.Troll.PROCESSED_SUBDIR = "processed"

# max files we should decompress at the same time
Hellanzb.Troll.MAX_DECOMPRESSION_THREADS = 2

# If any of the following file types are missing from the archive and cannot be repaired,
# continue processing because they're unimportant
Hellanzb.Troll.NOT_REQUIRED_FILE_TYPES = [ "m3u", "nfo", "sfv" ]

# music types we know about
defineMusicType("ape", "mac <FILE> <DESTFILE> -d")
defineMusicType("flac", "flac -d <FILE>")
defineMusicType("wav", None)
defineMusicType("mp3", None)

def usage():
    pass

def runDaemon():
    # start the daemon
    daemon = Hellanzb.Ziplick.Ziplick()

    # FIXME: move these elsewhere (top of this file or a config file and or cmd line
    # options)
    daemon.prefix = '/ext2/'
    #daemon.prefix = '/beans/tmp/ziplick/'
    daemon.dest = daemon.prefix + 'usenet/'
    daemon.working = daemon.prefix + 'nzb/daemon.working/'
    #daemon.working = '/beans/incoming/nzbget'
    daemon.queue = daemon.prefix + 'nzb/daemon.queue/'
    daemon.current = daemon.prefix + 'nzb/daemon.current/'
    daemon.temp = daemon.prefix + 'nzb/daemon.temp/'

    daemon.start()

def runTroll():
    try:
        if len(sys.argv) < 2:
            usage()
            sys.exit(1)
                
        incomingDir = sys.argv[1]

        Hellanzb.Troll.init()
        Hellanzb.Troll.troll(incomingDir)

    except FatalError, fe:
        Hellanzb.Troll.cleanUp(incomingDir)
        error("An unexpected problem occurred: " + fe.message + "\n")
        sys.exit(1)

    
if __name__ == '__main__':
    
    exe = os.path.basename(sys.argv[0])

    if exe == "hellanzb":
        runDaemon()
        
    elif exe == "troll":
        runTroll()
